name: 'Generate coverage report'

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  coverage:

    runs-on: [ubuntu-latest]
    name: Coverage on Ubuntu

    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          check-latest: true
          cache: 'maven'
      - name: Generate coverage with JaCoCo
        env:
          BROWSER: firefox-container
        run: mvn -V --color always -ntp clean verify jacoco:prepare-agent test integration-test jacoco:report '-Dgpg.skip'

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5.5.0
        with:
          token: ${{secrets.CODECOV_TOKEN}}